apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-apigw
spec:
  selector:
    matchLabels:
      app: learning-apigw
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: learning-apigw
    spec:
      containers:
      - name: learning-apigw
        image: ${REPOSITORY_TAG}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: develop
        imagePullPolicy: Never
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-learning-apigw

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: learning-apigw

  ports:
    - name: http
      port: 8080

  type: ClusterIP